export const GET_DATABASES_PERMISSIONS = 'GET_DATABASES_PERMISSIONS';

export const GET_TABLES_PERMISSIONS = 'GET_TABLES_PERMISSIONS';

export const UPDATE_DATABASES_PERMISSIONS = 'UPDATE_DATABASES_PERMISSIONS';

export const UPDATE_TABLES_PERMISSIONS = 'UPDATE_TABLES_PERMISSIONS';

export const SAVE_CHANGES = 'SAVE_CHANGES';

export const CANCEL_CHANGES = 'CANCEL_CHANGES';
