export const GET_DATABASES_PERMISSIONS = 'GET_DATABASES_PERMISSIONS';
export const GET_DATABASES_PERMISSIONS_SUCCESS = 'GET_DATABASES_PERMISSIONS_SUCCESS';
export const GET_DATABASES_PERMISSIONS_ERROR = 'GET_DATABASES_PERMISSIONS_SUCCESS';

export const GET_TABLES_PERMISSIONS = 'GET_TABLES_PERMISSIONS';
export const GET_TABLES_PERMISSIONS_SUCCESS = 'GET_TABLES_PERMISSIONS_SUCCESS';
export const GET_TABLES_PERMISSIONS_ERROR = 'GET_TABLES_PERMISSIONS_ERROR';

export const UPDATE_DATABASES_PERMISSIONS = 'UPDATE_DATABASES_PERMISSIONS';

export const UPDATE_TABLES_PERMISSIONS = 'UPDATE_TABLES_PERMISSIONS';

export const SAVE_CHANGES = 'SAVE_CHANGES';
export const SAVE_CHANGES_SUCCESS = 'SAVE_CHANGES_SUCCESS';
export const SAVE_CHANGES_ERROR = 'SAVE_CHANGES_ERROR';

export const CANCEL_CHANGES = 'CANCEL_CHANGES';
