export const GET_DATABASES_PERMISSIONS = 'GET_DATABASES_PERMISSIONS';
export const GET_DATABASES_PERMISSIONS_SUCCESS = 'GET_DATABASES_PERMISSIONS_SUCCESS';
export const GET_DATABASES_PERMISSIONS_ERROR = 'GET_DATABASES_PERMISSIONS_SUCCESS';

export const GET_COLLECTIONS_PERMISSIONS = 'GET_COLLECTIONS_PERMISSIONS';
export const GET_COLLECTIONS_PERMISSIONS_SUCCESS = 'GET_COLLECTIONS_PERMISSIONS_SUCCESS';
export const GET_COLLECTIONS_PERMISSIONS_ERROR = 'GET_COLLECTIONS_PERMISSIONS_SUCCESS';

export const GET_TABLES_PERMISSIONS = 'GET_TABLES_PERMISSIONS';
export const GET_TABLES_PERMISSIONS_SUCCESS = 'GET_TABLES_PERMISSIONS_SUCCESS';
export const GET_TABLES_PERMISSIONS_ERROR = 'GET_TABLES_PERMISSIONS_ERROR';

export const UPDATE_DATABASES_PERMISSIONS = 'UPDATE_DATABASES_PERMISSIONS';

export const UPDATE_TABLES_PERMISSIONS = 'UPDATE_TABLES_PERMISSIONS';

export const UPDATE_COLLECTIONS_PERMISSIONS = 'UPDATE_COLLECTIONS_PERMISSIONS';

export const SAVE_CHANGES = 'SAVE_CHANGES';
export const SAVE_CHANGES_SUCCESS = 'SAVE_CHANGES_SUCCESS';
export const SAVE_CHANGES_ERROR = 'SAVE_CHANGES_ERROR';

export const SAVE_COLLECTIONS_CHANGES = 'SAVE_COLLECTIONS_CHANGES';
export const SAVE_COLLECTIONS_CHANGES_SUCCESS = 'SAVE_COLLECTIONS_CHANGES_SUCCESS';
export const SAVE_COLLECTIONS_CHANGES_ERROR = 'SAVE_COLLECTIONS_CHANGES_ERROR';

export const CANCEL_CHANGES = 'CANCEL_CHANGES';

export const RESET_PERMISSIONS_STATE = 'RESET_PERMISSIONS_STATE';
