export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const HIDE_USER_UPDATE_MESSAGE = 'HIDE_USER_UPDATE_MESSAGE';
