export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_ERROR = 'GET_DASHBOARD_ERROR';

export const ADD_VISUALIZATIONS_TO_DASHBOARD = ' ADD_VISUALIZATIONS_TO_DASHBOARD';
export const ADD_VISUALIZATIONS_TO_DASHBOARD_SUCCESS = ' ADD_VISUALIZATIONS_TO_DASHBOARD_SUCCESS';
export const ADD_VISUALIZATIONS_TO_DASHBOARD_ERROR = ' ADD_VISUALIZATIONS_TO_DASHBOARD_ERROR';

export const UPDATE_DASHBOARD = 'UPDATE_DASHBOARD';
export const UPDATE_DASHBOARD_SUCCESS = 'UPDATE_DASHBOARD_SUCCESS';
export const UPDATE_DASHBOARD_ERROR = 'UPDATE_DASHBOARD_ERROR';
