export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const GET_COLLECTIONS_SUCCESS = 'GET_COLLECTIONS_SUCCESS';
export const GET_COLLECTIONS_ERROR = 'GET_COLLECTIONS_ERROR';

export const FETCH_VISUALIZATIONS = 'FETCH_VISUALIZATIONS';
export const FETCH_VISUALIZATIONS_SUCCESS = 'FETCH_VISUALIZATIONS_SUCCESS';
export const FETCH_VISUALIZATIONS_ERROR = 'FETCH_VISUALIZATIONS_ERROR';

export const DELETE_VISUALIZATION = 'DELETE_VISUALIZATION';
export const DELETE_DASHBOARD = 'DELETE_DASHBOARD';

export const ADD_DASHBOARD = 'ADD_DASHBOARD';

export const OPEN_MODAL = 'COLLECTION/OPEN_MODAL';
export const CLOSE_MODAL = 'COLLECTION/CLOSE_MODAL';
export const SET_FORM_DATA = 'COLLECTION/SET_FORM_DATA';
export const RESET_NOTIFICATION = 'COLLECTION/RESET_NOTIFICATION';

export const ADD_COLLECTION = 'ADD_COLLECTION';
export const ADD_COLLECTION_SUCCESS = 'ADD_COLLECTION_SUCCESS';
export const ADD_COLLECTION_ERROR = 'ADD_COLLECTION_ERROR';

export const MOVE_TO_COLLECTION = 'MOVE_TO_COLLECTION';
export const MOVE_TO_COLLECTION_SUCCESS = 'MOVE_TO_COLLECTION_SUCCESS';
export const MOVE_TO_COLLECTION_ERROR = 'MOVE_TO_COLLECTION_ERROR';

export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS';
export const DELETE_COLLECTION_ERROR = 'DELETE_COLLECTION_ERROR';

export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS';
export const UPDATE_COLLECTION_ERROR = 'UPDATE_COLLECTION_ERROR';

export const GET_CURRENT_COLLECTION = 'GET_CURRENT_COLLECTION';
export const GET_CURRENT_COLLECTION_SUCCESS = 'GET_CURRENT_COLLECTION_SUCCESS';
export const GET_CURRENT_COLLECTION_ERROR = 'GET_CURRENT_COLLECTION_ERROR';
