export const IS_LOADING = 'IS_LOADING';
export const RESET_ERROR = 'RESET_ERROR';
export const SET_ERROR = 'SET_ERROR';

export const GET_USER_GROUPS = 'GET_USER_GROUPS';
export const GET_USER_GROUPS_SUCCESS = 'GET_USER_GROUPS_SUCCESS';
export const GET_USER_GROUPS_ERROR = 'GET_USER_GROUPS_ERROR';

export const GET_USER_GROUP = 'GET_USER_GROUP';
export const GET_USER_GROUP_SUCCESS = 'GET_USER_GROUP_SUCCESS';
export const GET_USER_GROUP_ERROR = 'GET_USER_GROUP_ERROR';

export const ADD_USER_GROUP = 'ADD_USER_GROUP';
export const ADD_USER_GROUP_SUCCESS = 'ADD_USER_GROUP_SUCCESS';
export const ADD_USER_GROUP_ERROR = 'ADD_USER_GROUP_ERROR';

export const UPDATE_USER_GROUP = 'UPDATE_USER_GROUP';
export const UPDATE_USER_GROUP_SUCCESS = 'UPDATE_USER_GROUP_SUCCESS';
export const UPDATE_USER_GROUP_ERROR = 'UPDATE_USER_GROUP_ERROR';

export const DELETE_USER_GROUP = 'DELETE_USER_GROUP';
export const DELETE_USER_GROUP_SUCCESS = 'DELETE_USER_GROUP_SUCCESS';
export const DELETE_USER_GROUP_ERROR = 'DELETE_USER_GROUP_ERROR';

export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP';
export const ADD_USER_TO_GROUP_SUCCESS = 'ADD_USER_TO_GROUP_SUCCESS';
export const ADD_USER_TO_GROUP_ERROR = 'ADD_USER_TO_GROUP_ERROR';

export const DELETE_USER_FROM_GROUP = 'DELETE_USER_FROM_GROUP';
export const DELETE_USER_FROM_GROUP_SUCCESS = 'DELETE_USER_FROM_GROUP_SUCCESS';
export const DELETE_USER_FROM_GROUP_ERROR = 'DELETE_USER_FROM_GROUP_ERROR';
