export const IS_LOADING = 'IS_LOADING';
export const RESET_ERROR = 'RESET_ERROR';

export const GET_VISUALISATIONS = 'GET_VISUALISATIONS';
export const GET_VISUALISATIONS_SUCCESS = 'GET_VISUALISATIONS_SUCCESS';
export const GET_VISUALISATIONS_ERROR = 'GET_VISUALISATIONS_ERROR';

export const DELETE_VISUALISATIONS = 'DELETE_VISUALISATIONS';
export const DELETE_VISUALISATIONS_SUCCESS = 'DELETE_VISUALISATIONS_SUCCESS';
export const DELETE_VISUALISATIONS_ERROR = 'DELETE_VISUALISATIONS_ERROR';
