export const IS_DATASETS_LOADING = 'IS_DATASETS_LOADING';

export const GET_DATASETS = 'GET_DATASETS';
export const GET_DATASETS_SUCCESS = 'GET_DATASETS_SUCCESS';
export const GET_DATASETS_ERROR = 'GET_DATASETS_ERROR';

export const GET_TABLES = 'GET_TABLES';
export const GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS';
export const GET_TABLES_ERROR = 'GET_TABLES_ERROR';

export const GET_DATASET_ID = 'GET_DATASET_ID';
