export const IS_DATABASE_LOADING = 'IS_DATABASE_LOADING';

export const GET_DATABASES = 'GET_DATABASES';
export const GET_DATABASES_SUCCESS = 'GET_DATABASES_SUCCESS';
export const GET_DATABASES_ERROR = 'GET_DATABASES_ERROR';

export const DELETE_DATABASE = 'DELETE_DATABASE';
export const DELETE_DATABASE_SUCCESS = 'DELETE_DATABASE_SUCCESS';
export const DELETE_DATABASE_ERROR = 'DELETE_DATABASE_ERROR';
