export const IS_DATABASE_LOADING = 'IS_DATABASE_LOADING';

export const DELETE_DATABASE = 'DELETE_DATABASE';
export const DELETE_DATABASE_SUCCESS = 'DELETE_DATABASE_SUCCESS';
export const DELETE_DATABASE_ERROR = 'DELETE_DATABASE_ERROR';
