export const SET_VISUALIZATION = 'SET_VISUALIZATION';
export const SET_VISUALIZATION_IN_PROGRESS = 'SET_VISUALIZATION_IN_PROGRESS';
export const SET_VISUALIZATION_SUCCESS = 'SET_VISUALIZATION_SUCCESS';

export const FETCH_VISUALIZATION = 'FETCH_VISUALIZATION';
export const FETCH_VISUALIZATION_SUCCESS = 'FETCH_VISUALIZATION_SUCCESS';

export const UPDATE_VISUALIZATION_CONFIG = 'UPDATE_VISUALIZATION_CONFIG';

export const UPDATE_VISUALIZATION_NAME = 'UPDATE_VISUALIZATION_NAME';

export const VISUALIZATIONS_FETCHING = 'VISUALIZATIONS_FETCHING';

export const FETCH_DATA_AND_SCHEMA = 'FETCH_DATA_AND_SCHEMA';
export const FETCH_DATA_AND_SCHEMA_IN_PROGRESS = 'DATA_FETCHING_IN_PROGRESS';
export const FETCH_DATA_AND_SCHEMA_SUCCESS = 'FETCH_DATA_AND_SCHEMA_SUCCESS';
