export const SET_VISUALIZATION = 'SET_VISUALIZATION';

export const FETCH_VISUALIZATION = 'FETCH_VISUALIZATION';
export const FETCH_VISUALIZATION_SUCCESS = 'FETCH_VISUALIZATION_SUCCESS';

export const UPDATE_VISUALIZATION_CONFIG = 'UPDATE_VISUALIZATION_CONFIG';

export const UPDATE_VISUALIZATION_NAME = 'UPDATE_VISUALIZATION_NAME';

export const CREATE_VISUALIZATION = 'CREATE_VISUALIZATION';
