export const SET_VISUALIZATION = 'SET_VISUALIZATION';

export const UPDATE_VISUALIZATION_CONFIG = 'UPDATE_VISUALIZATION_CONFIG';

export const UPDATE_VISUALIZATION_NAME = 'UPDATE_VISUALIZATION_NAME';
