export const IS_LOADING = 'IS_LOADING';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const UPDATE_USER_FROM_LIST = 'UPDATE_USER_FROM_LIST';
export const UPDATE_USER_FROM_LIST_SUCCESS = 'UPDATE_USER_FROM_LIST_SUCCESS';
export const UPDATE_USER_FROM_LIST_ERROR = 'UPDATE_USER_FROM_LIST_ERROR';

export const TOGGLE_USER_STATUS = 'TOGGLE_USER_STATUS';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const SET_TEMPORARY_PASSWORD = 'SET_TEMPORARY_PASSWORD';
export const CLEAR_TEMPORARY_PASSWORD = 'CLEAR_TEMPORARY_PASSWORD';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const GET_MEMBERSHIPS = 'GET_MEMBERSHIPS';
export const GET_MEMBERSHIPS_SUCCESS = 'GET_MEMBERSHIPS_SUCCESS';
export const GET_MEMBERSHIPS_ERROR = 'GET_MEMBERSHIPS_ERROR';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const SET_FORM_DATA = 'SET_FORM_DATA';

export const SET_ACTIVE_TAB_INDEX = 'SET_ACTIVE_TAB_INDEX';
