name: Client Build
on:
  push:
    branches: [develop]
    paths: 'client/**/*.*'
env:
  CI: false
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: yarn
      - name: ESlint
        run: yarn lint
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: yarn build
      - name: Deploy to S3
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete