export const GET_ANALYTICS = 'GET_ANALYTICS';
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCCESS';
export const GET_ANALYTICS_ERROR = 'GET_ANALYTICS_ERROR';

export const DELETE_VISUALIZATION = 'DELETE_VISUALIZATION';
