export const GET_ANALYTICS = 'GET_ANALYTICS';
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCCESS';
export const GET_ANALYTICS_ERROR = 'GET_ANALYTICS_ERROR';

export const ADD_VISUALIZATION = 'ADD_VISUALIZATION';
export const DELETE_VISUALIZATION = 'DELETE_VISUALIZATION';

export const ADD_DASHBOARD = 'ADD_DASHBOARD';
export const DELETE_DASHBOARD = 'DELETE_DASHBOARD';
