export const GET_ANALYTICS = 'GET_ANALYTICS';
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCCESS';
export const GET_ANALYTICS_ERROR = 'GET_ANALYTICS_ERROR';

export const FETCH_VISUALIZATIONS = 'FETCH_VISUALIZATIONS';
export const FETCH_VISUALIZATIONS_SUCCESS = 'FETCH_VISUALIZATIONS_SUCCESS';
export const FETCH_VISUALIZATIONS_ERROR = 'FETCH_VISUALIZATIONS_ERROR';

export const DELETE_VISUALIZATION = 'DELETE_VISUALIZATION';
export const DELETE_DASHBOARD = 'DELETE_DASHBOARD';
